name: Tests

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  test:
    runs-on: ubuntu-latest
    env:
      TMPDIR: /tmp
      PYTHONPATH: ${{ github.workspace }}/src
      LOG_STD_OUT: true
      LOG_LEVEL: DEBUG
    permissions:
      contents: read
      
    steps:
      - uses: actions/checkout@v4
      
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'
          
      - name: Install Poetry
        uses: snok/install-poetry@v1
        
      - name: Install dependencies
        run: |
          poetry install
          poetry run pip install -e .
          
      - name: Install MCP CLI
        run: |
          # Install mcp-cli in editable mode
          poetry run pip install -e git+https://github.com/adamdude828/mcp-cli.git#egg=mcp-cli
          # Verify installation
          poetry run which mcp-cli || true
          poetry run mcp-cli --help || true
          
      - name: Install Playwright browsers
        run: |
          poetry run playwright install chromium
          poetry run playwright install-deps
        
      - name: Setup MCP CLI config
        run: |
          # Create config directory
          mkdir -p ~/.mcp-cli
          # Create config file
          cat > ~/.mcp-cli/server_config.json << 'EOF'
          {
            "mcpServers": {
              "playwright": {
                "command": "python",
                "args": [
                  "-m",
                  "playwright_mcp",
                  "--mode",
                  "both"
                ],
                "logging": {
                  "level": "DEBUG"
                }
              }
            }
          }
          EOF
          # Verify config
          cat ~/.mcp-cli/server_config.json
          
      - name: Create logs directory
        run: |
          mkdir -p logs
          chmod 777 logs
          ls -la logs
          
      - name: Run test
        run: |
          # Debug info
          echo "Current directory: $(pwd)"
          echo "Python path: $PYTHONPATH"
          echo "Log level: $LOG_LEVEL"
          echo "MCP CLI config location:"
          ls -la ~/.mcp-cli/
          
          # Start daemon and verify it's running
          poetry run mcp-cli --server playwright call-tool --tool start-daemon --tool-args '{}'
          sleep 2
          
          # Check daemon process
          echo "Checking daemon process with different patterns:"
          echo "Pattern 1 (browser_daemon$):"
          pgrep -f "playwright_mcp.browser_daemon$" || true
          echo "Pattern 2 (browser_daemon.browser_manager):"
          pgrep -f "playwright_mcp.browser_daemon.browser_manager" || true
          
          # Check socket file
          echo "Checking socket file:"
          ls -la /tmp/playwright_mcp.sock || true
          
          # Check logs
          echo "Checking logs:"
          ls -la logs/
          echo "Debug log contents:"
          cat logs/debug.log || true
          echo "Error log contents:"
          cat logs/error.log || true
          
          # Run test
          poetry run pytest tests/integration/test_execute_js.py::test_execute_simple_js -v
        
      - name: Cleanup Services
        if: always()
        run: |
          pkill -f "playwright_mcp.browser_daemon" || true
          pkill -f "python -m playwright_mcp" || true 