name: Tests

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'
          
      - name: Install Poetry
        uses: snok/install-poetry@v1
        
      - name: Install dependencies
        run: poetry install
        
      - name: Install Playwright browsers
        run: poetry run playwright install --with-deps
        
      - name: Run flake8
        run: poetry run flake8 src tests
        
      - name: Run pytest
        run: poetry run pytest 