name: Tests

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'
          
      - name: Install Poetry
        uses: snok/install-poetry@v1
        
      - name: Install dependencies
        run: poetry install
        
      - name: Install Playwright browsers
        run: poetry run playwright install --with-deps
        
      - name: Run flake8
        run: poetry run flake8 src tests

      - name: Start Browser Manager
        run: |
          poetry run python -m playwright_mcp.browser_manager &
          echo "Waiting for Browser Manager to start..."
          sleep 5
        
      - name: Start MCP Server
        run: |
          poetry run python -m playwright_mcp &
          echo "Waiting for MCP Server to start..."
          sleep 5
        
      - name: Run pytest
        run: poetry run pytest 
        
      - name: Cleanup Services
        if: always()
        run: |
          pkill -f "python -m playwright_mcp" || true
          pkill -f "playwright_mcp.browser_manager" || true 